version = 3
ScenarioInfo = {
    name = 'Nomads Mission 2: The Enemy of My Enemy',
    description = '<LOC SCMP_001_Description>Initial scans of the planet revealed evenly spaced hills, leading some to believe that the hills were ancient alien burial mounds. Subsequent scans disproved this theory, but many believe that the old Earth Empire actually found alien remains, spirited them away and then faked the scans as part of the cover-up.',
    type = 'campaign_coop',
    starts = true,
    preview = '',
    size = {1024, 1024},
    map = '/maps/NMCA_002/nomadbmwip.scmap',
    save = '/maps/NMCA_002/nomadbmwip_save.lua',
    script = '/maps/NMCA_002/nomadbmwip_script.lua',
    norushradius = 90.000000,
    norushoffsetX_Player1 = 0.000000,
    norushoffsetY_Player1 = 0.000000,
    norushoffsetX_Cybran = 0.000000,
    norushoffsetY_Cybran = 0.000000,
    norushoffsetX_CybranCivilian = 0.000000,
    norushoffsetY_CybranCivilian = 0.000000,
    norushoffsetX_UEF = 0.000000,
    norushoffsetY_UEF = 0.000000,
    norushoffsetX_Player2 = 0.000000,
    norushoffsetY_Player2 = 0.000000,
    norushoffsetX_Player3 = 0.000000,
    norushoffsetY_Player3 = 0.000000,
    norushoffsetX_Player4 = 0.000000,
    norushoffsetY_Player4 = 0.000000,
    norushoffsetX_NEUTRAL_CIVILIAN = 0.000000,
    norushoffsetY_NEUTRAL_CIVILIAN = 0.000000,
    norushoffsetX_Nomads = 0.000000,
    norushoffsetY_Nomads = 0.000000,
    Configurations = {
        ['standard'] = {
            teams = {
                { name = 'FFA', armies = {'Player1','Cybran','CybranCivilian','UEF','Player2','Player3','Player4','NEUTRAL_CIVILIAN','Nomads',} },
            },
            customprops = {
                ['ExtraArmies'] = STRING( 'ARMY_9 NEUTRAL_CIVILIAN' ),
            },
        },
    }}
